#!/usr/bin/ash

run_latehook() {
    local tag mountpath

    tag="${tag:-myfs}"
    mountflags="ro,noatime,nosuid"
    mountpath="/new_root/usr"

    mkdir "$mountpath"
    mount ${mountflags:+-o $mountflags} -t virtiofs "$tag" "$mountpath"
}

# vim: set ft=sh ts=4 sw=4 et:
